name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: carlosjoselopezsoriano/my-ecomerce-front
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  DOCKERFILE_PATH: Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del c√≥digo del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: karlostcp
          password: ${{ secrets.MI_PTA_DOCKERHUB2 }}

      # Paso 3: Construir la imagen de Docker usando el Dockerfile
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$SHA -f $DOCKERFILE_PATH .

      # Paso 4: Subir las etiquetas de la imagen a Docker Hub
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$SHA
